#!/bin/bash

mkdir -p output_dir

prefix="output_dir/$(date +%F-%T)"

echo "Outputs of this test will save in $prefix"
mkdir -p $prefix
for file in $(find ./OS_PJ1_Test/ -type f)
do
    n="$(head -n2 $file | tail -n1 | awk '{print $1}')"

    echo "=================="
    echo "Input File: $file "
    echo "=================="
    for i in {1..1}
    do
        echo "./main < $file > $prefix/${file:14:-4}_${i}_child.out"
        ./main < $file > $prefix/${file:14:-4}_${i}_child.out
        echo "./test $n > $prefix/${file:14:-4}_${i}_dmesg.out"
        ./test ${n} > $prefix/${file:14:-4}_${i}_dmesg.out
    done
done
