#!/bin/sh
# usage ./test [line_count]
dmesg | grep Project1 | tail -n$1 | sed 's/\[\s*[0-9]*.[0-9]*\]//'
dmesg | grep Project1 | tail -n$1 | sed 's/\[\s*[0-9]*.[0-9]*\]//' | awk '{print $2 ": " $4 - $3}' | sort
